### ISSUE TITLE
Gutschriften(credit notes) für steuerbefreite Kunden haben immer 0.00 Preise

### ISSUE THREAD

**Issue by pumpadump** [osiegmar/billomat4j#2]
Wenn man über billomat4j versucht eine CreditNote für einen als steuerbefreit markierten Kunden zu erstellen, werden alle Preise für alle Posten in der Gutschrift auf 0.00 gesetzt.

Ich weiß nicht ob das ein Bug in der billomat4j library oder der api ist.

**Comment by osiegmar** [comment]
Leider habe ich dieses Issue erst heute entdeckt, da ich keine E-Mail-Benachrichtigung dafür erhalten habe. Seitens billomat4j wird kein Wert default-mäßig auf 0.00 gesetzt. Das Problem besteht daher vermutlich in Billomat (oder in der Verwendung von billomat4j). Genaueres ließe sich mit einem Test / Beispielcode sagen.
